POST http://beta-wd3.gridsumdissector.com/api/3.0.0-beta/profile/getProfilesBySolutionId HTTP/1.1
Host: beta-wd3.gridsumdissector.com
Connection: keep-alive
Content-Length: 58
Accept: application/json, text/plain, */*
Origin: http://beta-wd3.gridsumdissector.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: http://beta-wd3.gridsumdissector.com/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6,ja;q=0.4
Cookie: GRIDSUMID=2c254f5f795a418faa272ef726349363; X-Gridsum-FullTicketId=TGT-41921-qnpXoNhqCKiCrtGcgfEgB2dEgezjfCic1d2Z474XlPkCbTc7ec-x-gridsumdissector; .AspNetCore.Session=CfDJ8GDLwiuBwbRJuB9C%2BoCjW%2BhqS1tI5QtRrD7PCsARf17h%2BC2b047%2BAcV8xOYWwZXuwnHbJOlKUnvCSmI1YbfU9r564rp62fh9P98P4HelqZldtgCfMufkHo0fZ676E22ILTlMTXhiRqj2UNNhEypOWvep5g7Nf6qMqTb9RVJR985i; _gscu_2045371801=73823411ohgnka16; _gscs_2045371801=74193168zc94oi16|pv:5; _gscbrs_2045371801=1

{"Paging":{"PageIndex":0,"PageSize":10},"SolutionId":2002}